name: Build and push

on:
  push:
    branches:
      - add-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./7.2-cli
          file: Dockerfile
          push: true
          tags: apliteni/keitaro-php:7.2-cli