name: Build and push

on:
  push:
    branches:
      - add-github-actions

jobs:
  php:
    strategy:
      fail-fast: false
      matrix:
        versions: [5.6-cli, 5.6-fpm, 7.1-fpm, 7.2-cli]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.versions }}
          file: ./${{ matrix.versions }}/Dockerfile
          tags: apliteni/keitaro-php:${{ matrix.versions }}